[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
strategy = "EUWvahvmdyPRgmwcFuqJdJ4FX8S2syWGc8XdTdafshZ2"
user_management = "BE2bDcazEUS5YpSW2JgJ2CAeTErp8LrpkZWAuW8WXa4h"
vault = "76MQ83iPkH4ERPWq8cDKwo7KaQrSpkdwF6qdTbHi7Q7j"

[programs.mainnet]
strategy = "STR1111111111111111111111111111111111111111"
user_management = "UMgmtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
vault = "VLT1111111111111111111111111111111111111111"

[programs.testnet]
strategy = "STR1111111111111111111111111111111111111111"
user_management = "UMgmtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
vault = "VLT1111111111111111111111111111111111111111"

[registry]
url = "https://api.github.com/repos/coral-xyz/anchor/releases/latest"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --timeout 1000000 tests/**/*.ts"
